CRAWLER_DIR = '/home/nano/PycharmProjects/beatTheBookie_crawler/beatTheBookie_crawler/crawler'
BET_DIR = '/home/nano/PycharmProjects/beatTheBookie_crawler/beatTheBookie_crawler/crawler/bets'
MATCH_DIR = '/home/nano/PycharmProjects/beatTheBookie_crawler/beatTheBookie_crawler/crawler/matches'
PROFITABLE_DIR = '/home/nano/PycharmProjects/beatTheBookie_crawler/beatTheBookie_crawler/crawler/profitables'
PAPERBET_DIR = '/home/nano/PycharmProjects/beatTheBookie_crawler/beatTheBookie_crawler/crawler/paperbet'
LOG_DIR = '/home/nano/PycharmProjects/beatTheBookie_crawler/beatTheBookie_crawler/crawler/logs'
