CRAWLER_DIR = r'D:\repos\beatTheBookie_crawler\beatTheBookie_crawler\crawler'
BET_DIR = r'D:\repos\beatTheBookie_crawler\beatTheBookie_crawler\crawler\bets'
MATCH_DIR = r'D:\repos\beatTheBookie_crawler\beatTheBookie_crawler\crawler\matches'
PROFITABLE_DIR = r'D:\repos\beatTheBookie_crawler\beatTheBookie_crawler\crawler\profitables'
PAPERBET_DIR = r'D:\repos\beatTheBookie_crawler\beatTheBookie_crawler\crawler\paperbet'
LOG_DIR = r'D:\repos\beatTheBookie_crawler\beatTheBookie_crawler\crawler\logs'
